name: Run benchmark

on: [push, pull_request]

jobs:
  bench:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bench.sh
        run: |
          # add permissions as bench.sh might not be executable yet
          chmod +x bench.sh
          ./bench.sh